services:
  scala-service:
    build:
      context: .
      dockerfile: scala/Dockerfile
    environment:
      SERVICE_NAME: scala-service
    ports:
      - "8081:8080"
  java-service:
    build:
      context: .
      dockerfile: java/Dockerfile
    environment:
      SERVICE_NAME: java-service
    ports:
      - "8082:8080"
