<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SmithyService>alloy.test#PizzaAdminService</SmithyService>
    <SmithyGeneratedNamespaces>alloy.test</SmithyGeneratedNamespaces>
    <SmithyGenerateServer>false</SmithyGenerateServer>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RestorePackagesPath>$(MSBuildProjectDirectory)/obj/packages</RestorePackagesPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSmithy.Client" Version="0.3.0-SNAPSHOT" />
    <PackageReference Include="NSmithy.Codecs.Json" Version="0.3.0-SNAPSHOT" />
    <PackageReference Include="NSmithy.Protocols.RestJson" Version="0.3.0-SNAPSHOT" />
    <ProjectReference Include="../contracts/NSmithy.Examples.SimpleRestJson.Contracts.csproj" />
  </ItemGroup>
</Project>
