<Project>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="10.0.11" />
    <PackageVersion Include="NSwag.ApiDescription.Client" Version="14.7.1" />
    <PackageVersion Include="Microsoft.Extensions.ApiDescription.Client" Version="10.0.0" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.11.3" />
    <PackageVersion Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
    <PackageVersion Include="System.Formats.Cbor" Version="9.0.4" />
    <PackageVersion Include="System.IO.Hashing" Version="9.0.4" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.Build.Framework" Version="18.3.3" />
    <PackageVersion Include="Microsoft.Build.Utilities.Core" Version="18.3.3" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
