<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SmithyService>example.weather#Weather</SmithyService>
    <SmithyGeneratedNamespaces>example.weather</SmithyGeneratedNamespaces>
    <SmithyGenerateServer>false</SmithyGenerateServer>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RestorePackagesPath>$(MSBuildProjectDirectory)/obj/packages</RestorePackagesPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSmithy.Client" Version="0.0.0-SNAPSHOT" />
    <PackageReference Include="NSmithy.Codecs.Json" Version="0.0.0-SNAPSHOT" />
    <PackageReference Include="NSmithy.Protocols.RestJson" Version="0.0.0-SNAPSHOT" />
    <PackageReference Include="OpenTelemetry" Version="1.16.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.16.0" />
    <ProjectReference Include="../contracts/NSmithy.Examples.RestJson1.Contracts.csproj" />
  </ItemGroup>
</Project>
