[workspace]
authors = ["Thomas Laich <thomaslaich@gmail.com>"]
channels = ["conda-forge"]
name = "simple-rest-json"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
openjdk = ">=25.0.2,<26"
smithy = ">=1.70.0,<2"
python = ">=3.11,<4"
