<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Bench.Stacks.GrpcNet</RootNamespace>
    <AssemblyName>Bench.Stack.GrpcNet</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Google.Protobuf" />
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../../contract/proto/GrpcBenchmarkService.proto" GrpcServices="Both" />
  </ItemGroup>
</Project>
