/*
 * Emits a proto3 .proto file for a service annotated with the alloy `@grpc`
 * trait. Mirrors `NSmithy.CodeGeneration.Proto.ProtoShapeGenerator`.
 *
 * Conventions:
 *   - Every member of a structure/error/union targeted by the service must
 *     carry an alloy `@protoIndex` trait (1-based field number).
 *   - Output path: `<csharp-namespace lowercased + slashes>/<ServiceName>.proto`.
 *   - Emits `option csharp_namespace = "{cs-ns}.Grpc";`.
 *   - Maps Smithy primitives to proto3 wire types; unions become `oneof`.
 */
package io.github.thomaslaich.smithy.csharp.codegen.generators;

import io.github.thomaslaich.smithy.csharp.codegen.CSharpNaming;
import io.github.thomaslaich.smithy.csharp.codegen.GenerationContext;
import io.github.thomaslaich.smithy.csharp.codegen.TraitIds;
import io.github.thomaslaich.smithy.csharp.codegen.support.ShapeSupport;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import software.amazon.smithy.codegen.core.CodegenException;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.knowledge.TopDownIndex;
import software.amazon.smithy.model.node.Node;
import software.amazon.smithy.model.shapes.EnumShape;
import software.amazon.smithy.model.shapes.IntEnumShape;
import software.amazon.smithy.model.shapes.ListShape;
import software.amazon.smithy.model.shapes.MapShape;
import software.amazon.smithy.model.shapes.MemberShape;
import software.amazon.smithy.model.shapes.OperationShape;
import software.amazon.smithy.model.shapes.ServiceShape;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.shapes.ShapeId;
import software.amazon.smithy.model.shapes.ShapeType;
import software.amazon.smithy.model.shapes.StructureShape;
import software.amazon.smithy.model.shapes.UnionShape;
import software.amazon.smithy.model.traits.DefaultTrait;
import software.amazon.smithy.model.traits.SparseTrait;
import software.amazon.smithy.utils.SmithyInternalApi;

@SmithyInternalApi
public final class ProtoGenerator {

  private static final ShapeId UNIT = ShapeId.from("smithy.api#Unit");

  private final GenerationContext context;
  private final ServiceShape service;

  public ProtoGenerator(GenerationContext context, ServiceShape service) {
    this.context = context;
    this.service = service;
  }

  public void run() {
    Model model = context.model();
    TopDownIndex idx = TopDownIndex.of(model);
    List<OperationShape> operations =
        idx.getContainedOperations(service).stream()
            .sorted(Comparator.comparing(o -> o.getId().toString()))
            .toList();

    String csharpNs = context.settings().csharpNamespace(service.getId().getNamespace());
    String serviceName = CSharpNaming.typeName(service.getId().getName());
    String dir = csharpNs.replace('.', '/');
    String path = dir + "/" + serviceName + ".proto";

    Set<ShapeId> referenced = collectReferencedShapes(model, operations);
    boolean usesEmpty =
        operations.stream()
            .anyMatch(op -> isUnit(op.getInputShape()) || isUnit(op.getOutputShape()));

    StringBuilder sb = new StringBuilder();
    sb.append("// <auto-generated />\n");
    sb.append("// Generated by smithy-csharp-codegen. DO NOT EDIT.\n");
    sb.append("syntax = \"proto3\";\n\n");
    sb.append("package ").append(service.getId().getNamespace()).append(";\n\n");
    sb.append("option csharp_namespace = \"").append(csharpNs).append(".Grpc\";\n\n");
    if (usesEmpty) {
      sb.append("import \"google/protobuf/empty.proto\";\n\n");
    }

    // service
    sb.append("service ").append(serviceName).append(" {\n");
    for (OperationShape op : operations) {
      sb.append("  rpc ").append(CSharpNaming.typeName(op.getId().getName())).append(" (");
      sb.append(messageType(op.getInputShape()));
      sb.append(") returns (");
      sb.append(messageType(op.getOutputShape()));
      sb.append(");\n");
    }
    sb.append("}\n\n");

    // referenced shapes: enums, structures, unions
    List<Shape> ordered =
        referenced.stream()
            .map(model::expectShape)
            .sorted(Comparator.comparing(s -> s.getId().toString()))
            .toList();
    for (Shape s : ordered) {
      switch (s.getType()) {
        case ENUM -> writeEnum(sb, (EnumShape) s);
        case INT_ENUM -> writeIntEnum(sb, (IntEnumShape) s);
        case STRUCTURE -> writeMessage(sb, model, (StructureShape) s);
        case UNION -> writeUnionMessage(sb, model, (UnionShape) s);
        default -> {
          /* lists/maps inline */
        }
      }
    }

    context.fileManifest().writeFile(path, sb.toString());
  }

  // ---------------- collection ----------------

  private Set<ShapeId> collectReferencedShapes(Model model, List<OperationShape> operations) {
    Set<ShapeId> result = new LinkedHashSet<>();
    Set<ShapeId> seen = new HashSet<>();
    for (OperationShape op : operations) {
      collect(model, op.getInputShape(), result, seen);
      collect(model, op.getOutputShape(), result, seen);
      for (ShapeId errId : op.getErrors()) collect(model, errId, result, seen);
    }
    return result;
  }

  private void collect(Model model, ShapeId id, Set<ShapeId> result, Set<ShapeId> seen) {
    if (isUnit(id) || !seen.add(id)) return;
    Shape s = model.expectShape(id);
    switch (s.getType()) {
      case STRUCTURE, UNION, ENUM, INT_ENUM -> {
        result.add(id);
        for (MemberShape m : s.members()) collect(model, m.getTarget(), result, seen);
      }
      case LIST, SET -> collect(model, ((ListShape) s).getMember().getTarget(), result, seen);
      case MAP -> {
        collect(model, ((MapShape) s).getKey().getTarget(), result, seen);
        collect(model, ((MapShape) s).getValue().getTarget(), result, seen);
      }
      default -> {}
    }
  }

  // ---------------- emission ----------------

  private void writeEnum(StringBuilder sb, EnumShape e) {
    String name = CSharpNaming.typeName(e.getId().getName());
    sb.append("enum ").append(name).append(" {\n");
    sb.append("  ").append(name).append("_UNSPECIFIED = 0;\n");
    int idx = 1;
    for (var entry : e.getEnumValues().entrySet()) {
      sb.append("  ")
          .append(name)
          .append("_")
          .append(entry.getKey().toUpperCase())
          .append(" = ")
          .append(idx++)
          .append(";\n");
    }
    sb.append("}\n\n");
  }

  private void writeIntEnum(StringBuilder sb, IntEnumShape e) {
    String name = CSharpNaming.typeName(e.getId().getName());
    sb.append("enum ").append(name).append(" {\n");
    sb.append("  ").append(name).append("_UNSPECIFIED = 0;\n");
    for (var entry : e.getEnumValues().entrySet()) {
      sb.append("  ")
          .append(name)
          .append("_")
          .append(entry.getKey().toUpperCase())
          .append(" = ")
          .append(entry.getValue())
          .append(";\n");
    }
    sb.append("}\n\n");
  }

  private void writeMessage(StringBuilder sb, Model model, StructureShape s) {
    sb.append("message ").append(CSharpNaming.typeName(s.getId().getName())).append(" {\n");
    List<MemberShape> members = new ArrayList<>(s.members());
    members.sort(Comparator.comparingInt(this::protoIndex));
    for (MemberShape m : members) writeField(sb, model, m, false);
    sb.append("}\n\n");
  }

  private void writeUnionMessage(StringBuilder sb, Model model, UnionShape u) {
    String name = CSharpNaming.typeName(u.getId().getName());
    sb.append("message ").append(name).append(" {\n");
    sb.append("  oneof value {\n");
    List<MemberShape> members = new ArrayList<>(u.members());
    members.sort(Comparator.comparingInt(this::protoIndex));
    for (MemberShape m : members) {
      int i = protoIndex(m);
      sb.append("    ")
          .append(protoFieldType(model, m, true))
          .append(" ")
          .append(camelToSnake(m.getMemberName()))
          .append(" = ")
          .append(i)
          .append(";\n");
    }
    sb.append("  }\n");
    sb.append("}\n\n");
  }

  private void writeField(StringBuilder sb, Model model, MemberShape m, boolean inOneOf) {
    int i = protoIndex(m);
    Shape target = model.expectShape(m.getTarget());
    String label = "";
    if (target.getType() == ShapeType.LIST || target.getType() == ShapeType.SET) {
      label = "repeated ";
    } else if (target.getType() == ShapeType.MAP) {
      // map<K, V> – no label
    } else if (!inOneOf && isProtoOptional(model, m)) {
      label = "optional ";
    }
    sb.append("  ")
        .append(label)
        .append(protoFieldType(model, m, false))
        .append(" ")
        .append(camelToSnake(m.getMemberName()))
        .append(" = ")
        .append(i)
        .append(";\n");
  }

  private String protoFieldType(Model model, MemberShape m, boolean unionInner) {
    Shape target = model.expectShape(m.getTarget());
    return switch (target.getType()) {
      case LIST, SET -> protoScalarOrRef(model, ((ListShape) target).getMember());
      case MAP -> {
        MapShape map = (MapShape) target;
        yield "map<"
            + protoScalarOrRef(model, map.getKey())
            + ", "
            + protoScalarOrRef(model, map.getValue())
            + ">";
      }
      default -> protoScalarOrRefById(target);
    };
  }

  private String protoScalarOrRef(Model model, MemberShape m) {
    return protoScalarOrRefById(model.expectShape(m.getTarget()));
  }

  private String protoScalarOrRefById(Shape s) {
    return switch (s.getType()) {
      case BOOLEAN -> "bool";
      case BYTE, SHORT, INTEGER -> "int32";
      case LONG -> "int64";
      case FLOAT -> "float";
      case DOUBLE -> "double";
      case STRING -> "string";
      case BLOB -> "bytes";
      case TIMESTAMP -> "int64";
      case BIG_INTEGER, BIG_DECIMAL -> "string";
      default -> CSharpNaming.typeName(s.getId().getName());
    };
  }

  private boolean isProtoOptional(Model model, MemberShape m) {
    if (ShapeSupport.isRequired(m)) return false;
    if (m.hasTrait(DefaultTrait.class)) return false;
    Shape target = model.expectShape(m.getTarget());
    return switch (target.getType()) {
      case STRING,
          BLOB,
          BOOLEAN,
          BYTE,
          SHORT,
          INTEGER,
          LONG,
          FLOAT,
          DOUBLE,
          TIMESTAMP,
          ENUM,
          INT_ENUM ->
          true;
      default -> false;
    };
  }

  private int protoIndex(MemberShape m) {
    return m.findTrait(TraitIds.PROTO_INDEX)
        .map(t -> ((Node) t.toNode()).expectNumberNode().getValue().intValue())
        .orElseThrow(
            () ->
                new CodegenException(
                    "Member " + m.getId() + " is missing required @protoIndex trait."));
  }

  private String messageType(ShapeId id) {
    if (isUnit(id)) return "google.protobuf.Empty";
    return CSharpNaming.typeName(id.getName());
  }

  private static boolean isUnit(ShapeId id) {
    return UNIT.equals(id);
  }

  private static String camelToSnake(String name) {
    StringBuilder sb = new StringBuilder();
    for (int i = 0; i < name.length(); i++) {
      char c = name.charAt(i);
      if (i > 0
          && Character.isUpperCase(c)
          && (Character.isLowerCase(name.charAt(i - 1))
              || (i + 1 < name.length() && Character.isLowerCase(name.charAt(i + 1))))) {
        sb.append('_');
      }
      sb.append(Character.toLowerCase(c));
    }
    return sb.toString();
  }

  // suppresses "unused import" warning if SparseTrait is not needed in some configurations
  @SuppressWarnings("unused")
  private static final Class<?> KEEP_SPARSE = SparseTrait.class;
}
