/*
 * Specialized SymbolWriter for C#. Mirrors PythonWriter / TypeScriptWriter:
 * supports the $T formatter for Symbol references, exposes addImport(String)
 * for raw namespace imports, and emits a generated-code banner plus collected
 * `using` directives via ImportDeclarations.
 *
 * $T behaviour:
 *  - Symbol with empty namespace: bare name (used for C# keyword primitives
 *    like `string`, `int`, etc.).
 *  - Symbol with non-empty namespace: name only; the namespace is added to the
 *    file imports. (System.* is also imported as a `using` to keep generated
 *    code uncluttered.)
 */
package io.github.thomaslaich.nsmithy.csharp.codegen.writer;

import java.util.function.BiFunction;
import software.amazon.smithy.codegen.core.CodegenException;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolReference;
import software.amazon.smithy.codegen.core.SymbolWriter;
import software.amazon.smithy.utils.SmithyUnstableApi;

@SmithyUnstableApi
public final class CSharpWriter extends SymbolWriter<CSharpWriter, ImportDeclarations> {

  private final String namespace;

  public CSharpWriter(String namespace) {
    super(new ImportDeclarations(namespace));
    this.namespace = namespace;
    trimBlankLines();
    trimTrailingSpaces();
    putFormatter('T', new CSharpSymbolFormatter());
  }

  /** Add a raw C# namespace as a `using` directive. */
  public CSharpWriter addImport(String csharpNamespace) {
    getImportContainer().importNamespace(csharpNamespace);
    return this;
  }

  /**
   * Override of {@code openBlock} that emits Allman-style braces for C#: a header ending with
   * {@code " {"} is split so the opening brace appears on its own line. Lambda bodies (ending with
   * {@code "=> {"}) and headers that don't end with {@code " {"} are left untouched.
   *
   * <p>All other {@code openBlock} overloads in {@code AbstractCodeWriter} delegate to this one.
   */
  @Override
  public CSharpWriter openBlock(
      String textBeforeNewline, String textAfterNewline, Object[] args, Runnable f) {
    if (shouldSplitBrace(textBeforeNewline)) {
      String header = textBeforeNewline.substring(0, textBeforeNewline.length() - 2);
      write(header, args);
      return super.openBlock("{", textAfterNewline, new Object[] {}, f);
    }
    return super.openBlock(textBeforeNewline, textAfterNewline, args, f);
  }

  private static boolean shouldSplitBrace(String text) {
    if (text == null || !text.endsWith(" {")) {
      return false;
    }
    // Preserve K&R-style braces for lambda bodies (e.g. "x => {").
    return !text.endsWith("=> {");
  }

  /** Factory used by WriterDelegator. */
  public static final class CSharpWriterFactory implements SymbolWriter.Factory<CSharpWriter> {
    @Override
    public CSharpWriter apply(String filename, String namespace) {
      return new CSharpWriter(namespace);
    }
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("// <auto-generated />\n");
    sb.append("// Generated by smithy-csharp-codegen. DO NOT EDIT.\n");
    sb.append("#nullable enable\n\n");
    sb.append(getImportContainer().toString());
    sb.append("namespace ").append(namespace).append(";\n\n");
    sb.append(super.toString());
    return sb.toString();
  }

  private final class CSharpSymbolFormatter implements BiFunction<Object, String, String> {
    @Override
    public String apply(Object type, String indent) {
      if (type instanceof Symbol s) {
        addImport(s, null);
        return s.getName();
      }
      if (type instanceof SymbolReference ref) {
        addImport(ref.getSymbol(), ref.getAlias(), SymbolReference.ContextOption.USE);
        return ref.getAlias();
      }
      throw new CodegenException("Invalid type for $T: " + type);
    }
  }
}
