<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace></RootNamespace>
    <AssemblyName>Bench.Stack.NSmithyGrpc</AssemblyName>
    <SmithyGenerateClient>true</SmithyGenerateClient>
    <SmithyGenerateServer>true</SmithyGenerateServer>
    <SmithyBuildFile>smithy-build.json</SmithyBuildFile>
    <SmithyBuildOutputPath>$(BaseIntermediateOutputPath)Smithy/</SmithyBuildOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../../packages/NSmithy.Client/NSmithy.Client.csproj" />
    <ProjectReference Include="../../../packages/NSmithy.Codecs.Proto/NSmithy.Codecs.Proto.csproj" />
    <ProjectReference Include="../../../packages/NSmithy.Core/NSmithy.Core.csproj" />
    <ProjectReference Include="../../../packages/NSmithy.Http/NSmithy.Http.csproj" />
    <ProjectReference Include="../../../packages/NSmithy.MSBuild/NSmithy.MSBuild.csproj" />
    <ProjectReference Include="../../../packages/NSmithy.Protocols.Grpc/NSmithy.Protocols.Grpc.csproj" />
    <ProjectReference Include="../../../packages/NSmithy.Server.AspNetCore/NSmithy.Server.AspNetCore.csproj" />
  </ItemGroup>

  <Import Project="../../../packages/NSmithy.MSBuild/Targets/NSmithy.MSBuild.targets" />

  <Target
    Name="_PublishBenchmarkProto"
    DependsOnTargets="GenerateSmithyCode"
    AfterTargets="GenerateSmithyCode"
  >
    <ItemGroup>
      <_BenchProto Include="$(SmithyBuildOutputPath)source/proto-codegen/**/*.proto" />
    </ItemGroup>
    <Copy
      SourceFiles="@(_BenchProto)"
      DestinationFolder="$(MSBuildThisFileDirectory)../../contract/proto"
      SkipUnchangedFiles="true"
      Condition="'@(_BenchProto)' != ''"
    />
  </Target>
</Project>
