<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
    <RestorePackagesPath>$(MSBuildProjectDirectory)/obj/packages</RestorePackagesPath>
    <VersionPrefix>0.6.0</VersionPrefix>
    <VersionSuffix>SNAPSHOT</VersionSuffix>
    <SmithyPublish>true</SmithyPublish>
    <SmithyMavenGroupId>io.github.thomaslaich.nsmithy.examples</SmithyMavenGroupId>
    <SmithyMavenArtifactId>rest-json1</SmithyMavenArtifactId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSmithy.MSBuild" Version="0.6.0-SNAPSHOT" />
  </ItemGroup>
</Project>
