<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../packages/NSmithy.Protocols.RestJson/NSmithy.Protocols.RestJson.csproj" />
    <ProjectReference Include="../../packages/NSmithy.Server.Mcp/NSmithy.Server.Mcp.csproj" />
  </ItemGroup>
</Project>
