package io.github.thomaslaich.nsmithy.proto.codegen;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import software.amazon.smithy.build.FileManifest;
import software.amazon.smithy.build.PluginContext;
import software.amazon.smithy.model.Model;
import software.amazon.smithy.model.node.Node;
import software.amazon.smithy.model.node.ObjectNode;

final class ProtoCodegenPluginTest {

  private static final String ALLOY_PROTO_TRAITS =
      """
      $version: "2"

      namespace alloy.proto

      use smithy.api#trait

      @trait(selector: "service")
      structure grpc {}

      @trait(selector: "member")
      integer protoIndex

      @trait(selector: "union")
      structure protoInlinedOneOf {}
      """;

  private static final String MODEL =
      """
      $version: "2"

      namespace example.oneof

      use alloy.proto#grpc
      use alloy.proto#protoIndex
      use alloy.proto#protoInlinedOneOf

      @grpc
      service ExampleService {
          version: "1"
          operations: [Choose]
      }

      operation Choose {
          input: ChoiceInput
          output: ChoiceInput
      }

      structure ChoiceInput {
          @protoIndex(2)
          selector: Choice
      }

      @protoInlinedOneOf
      union Choice {
          @protoIndex(3)
          byName: String

          @protoIndex(4)
          byCount: Integer
      }
      """;

  private static final String STREAMING_MODEL =
      """
      $version: "2"

      namespace example.streaming

      use alloy.proto#grpc
      use alloy.proto#protoIndex

      @grpc
      service StreamingService {
          version: "1"
          operations: [Watch]
      }

      operation Watch {
          input: WatchInput
          output: WatchOutput
      }

      structure WatchInput {
          @protoIndex(1)
          events: WatchInputEvent
      }

      @streaming
      union WatchInputEvent {
          @protoIndex(1)
          filter: WatchFilter
      }

      structure WatchFilter {
          @required
          @protoIndex(1)
          prefix: String
      }

      structure WatchOutput {
          @protoIndex(1)
          events: WatchOutputEvent
      }

      @streaming
      union WatchOutputEvent {
          @protoIndex(1)
          reading: WatchReading
      }

      structure WatchReading {
          @required
          @protoIndex(1)
          name: String
      }
      """;

  @TempDir Path tempDir;

  @Test
  void executeGeneratesExpectedProtoFileFromSmithyModel() throws Exception {
    Model model =
        Model.assembler()
            .addUnparsedModel("alloy-proto-traits.smithy", ALLOY_PROTO_TRAITS)
            .addUnparsedModel("model.smithy", MODEL)
            .assemble()
            .unwrap();
    FileManifest manifest = FileManifest.create(tempDir);

    new ProtoCodegenPlugin()
        .execute(
            PluginContext.builder()
                .model(model)
                .fileManifest(manifest)
                .settings(
                    ObjectNode.builder()
                        .withMember("service", Node.from("example.oneof#ExampleService"))
                        .withMember("baseNamespace", Node.from("My.Base"))
                        .build())
                .build());

    Path protoPath = Path.of("My/Base/Example/Oneof/ExampleService.proto");
    assertTrue(manifest.hasFile(protoPath));
    assertEquals(
        """
        // <auto-generated />
        // Generated by smithy-proto-codegen. DO NOT EDIT.
        syntax = "proto3";

        package example.oneof;

        option csharp_namespace = "My.Base.Example.Oneof.Grpc";

        service ExampleService {
          rpc Choose (ChoiceInput) returns (ChoiceInput);
        }

        message ChoiceInput {
          oneof selector {
            string by_name = 3;
            int32 by_count = 4;
          }
        }

        """,
        Files.readString(tempDir.resolve(protoPath)));
  }

  @Test
  void executeUsesStreamingUnionTargetsForGrpcStreams() throws Exception {
    Model model =
        Model.assembler()
            .addUnparsedModel("alloy-proto-traits.smithy", ALLOY_PROTO_TRAITS)
            .addUnparsedModel("model.smithy", STREAMING_MODEL)
            .assemble()
            .unwrap();
    FileManifest manifest = FileManifest.create(tempDir);

    new ProtoCodegenPlugin()
        .execute(
            PluginContext.builder()
                .model(model)
                .fileManifest(manifest)
                .settings(
                    ObjectNode.builder()
                        .withMember("service", Node.from("example.streaming#StreamingService"))
                        .build())
                .build());

    String proto = Files.readString(tempDir.resolve("Example/Streaming/StreamingService.proto"));
    assertTrue(
        proto.contains("  rpc Watch (stream WatchInputEvent) returns (stream WatchOutputEvent);"),
        proto);
  }
}
