[workspace]
authors = ["Thomas Laich <thomaslaich@gmail.com>"]
channels = ["conda-forge"]
name = "simplerestjson"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<4"
