<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <SmithyService>example.hello#HelloService</SmithyService>
    <SmithyGeneratedNamespaces>example.hello</SmithyGeneratedNamespaces>
    <!--#if (WithDocs && IsRestJson1)-->
    <SmithyGenerateDocs>true</SmithyGenerateDocs>
    <SmithyOpenApiProtocol>aws.protocols#restJson1</SmithyOpenApiProtocol>
    <!--#elif (WithDocs)-->
    <SmithyGenerateDocs>true</SmithyGenerateDocs>
    <!--#endif-->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NSmithy.Server.AspNetCore" Version="0.5.0" />
    <!--#if (WithDocs)-->
    <PackageReference Include="NSmithy.Server.AspNetCore.Docs" Version="0.5.0" />
    <!--#endif-->
    <!--#if (IsGrpc)-->
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.71.0" PrivateAssets="all" />
    <!--#endif-->
    <!--#if (WithContracts)-->
    <ProjectReference Include="../ContractsName/ContractsName.csproj" />
    <!--#endif-->
  </ItemGroup>

</Project>
