name: CI
on:
  push:
    branches:
      - master
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - name: Configure devenv cache
        uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv
        run: nix profile add nixpkgs#devenv
      - name: Build and test
        run: devenv shell -- just ci
