/*
 * Specialized SymbolWriter for C#. Mirrors PythonWriter / TypeScriptWriter:
 * supports the $T formatter for Symbol references, exposes addImport(String)
 * for raw namespace imports, and emits a generated-code banner plus collected
 * `using` directives via ImportDeclarations.
 *
 * $T behaviour:
 *  - Symbol with empty namespace: bare name (used for C# keyword primitives
 *    like `string`, `int`, etc.).
 *  - Symbol with non-empty namespace: name only; the namespace is added to the
 *    file imports. (System.* is also imported as a `using` to keep generated
 *    code uncluttered.)
 */
package io.github.thomaslaich.nsmithy.csharp.codegen.writer;

import java.util.Map;
import java.util.function.BiFunction;
import software.amazon.smithy.codegen.core.CodegenException;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolReference;
import software.amazon.smithy.codegen.core.SymbolWriter;
import software.amazon.smithy.model.shapes.Shape;
import software.amazon.smithy.model.traits.DocumentationTrait;
import software.amazon.smithy.utils.SmithyUnstableApi;

@SmithyUnstableApi
public final class CSharpWriter extends SymbolWriter<CSharpWriter, ImportDeclarations> {

  private final String namespace;

  public CSharpWriter(String namespace) {
    super(new ImportDeclarations(namespace));
    this.namespace = namespace;
    trimBlankLines();
    trimTrailingSpaces();
    putFormatter('T', new CSharpSymbolFormatter());
  }

  /** Add a raw C# namespace as a `using` directive. */
  public CSharpWriter addImport(String csharpNamespace) {
    getImportContainer().importNamespace(csharpNamespace);
    return this;
  }

  /** Emits a C# XML documentation summary from a Smithy shape's documentation trait. */
  public void writeXmlDocs(Shape shape) {
    shape.getTrait(DocumentationTrait.class).ifPresent(trait -> writeXmlDocs(trait.getValue()));
  }

  /**
   * Emits a C# XML documentation summary and parameter tags. Parameter names must match the
   * generated C# declaration.
   */
  public void writeXmlDocs(Shape shape, Map<String, String> parameterDocs) {
    shape
        .getTrait(DocumentationTrait.class)
        .ifPresentOrElse(
            trait -> writeXmlDocs(trait.getValue(), parameterDocs),
            () -> writeXmlDocs((String) null, parameterDocs));
  }

  /** Emits C# XML documentation parameter tags without a summary. */
  public void writeXmlParamDocs(Map<String, String> parameterDocs) {
    writeXmlDocs((String) null, parameterDocs);
  }

  private void writeXmlDocs(String summary) {
    writeXmlDocs(summary, Map.of());
  }

  public void writeXmlDocs(String summary, Map<String, String> parameterDocs) {
    boolean hasSummary = summary != null && !summary.isBlank();
    if (hasSummary) {
      write("/// <summary>");
      writeXmlText(summary);
      write("/// </summary>");
    }
    parameterDocs.forEach(
        (name, documentation) -> {
          if (documentation == null || documentation.isBlank()) {
            return;
          }
          write("/// <param name=\"$L\">", escapeXml(name));
          writeXmlText(documentation);
          write("/// </param>");
        });
  }

  private void writeXmlText(String text) {
    for (String line : text.strip().split("\\R", -1)) {
      if (line.isBlank()) {
        write("///");
      } else {
        write("/// $L", escapeXml(line.strip()));
      }
    }
  }

  private static String escapeXml(String value) {
    return value
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("\"", "&quot;");
  }

  /** Factory used by WriterDelegator. */
  public static final class CSharpWriterFactory implements SymbolWriter.Factory<CSharpWriter> {
    @Override
    public CSharpWriter apply(String filename, String namespace) {
      return new CSharpWriter(namespace);
    }
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("// <auto-generated />\n");
    sb.append("// Generated by smithy-csharp-codegen. DO NOT EDIT.\n");
    sb.append("#nullable enable\n\n");
    sb.append(getImportContainer().toString());
    sb.append("namespace ").append(namespace).append(";\n\n");
    sb.append(super.toString());
    return sb.toString();
  }

  private final class CSharpSymbolFormatter implements BiFunction<Object, String, String> {
    @Override
    public String apply(Object type, String indent) {
      if (type instanceof Symbol s) {
        addImport(s, null);
        return s.getName();
      }
      if (type instanceof SymbolReference ref) {
        addImport(ref.getSymbol(), ref.getAlias(), SymbolReference.ContextOption.USE);
        return ref.getAlias();
      }
      throw new CodegenException("Invalid type for $T: " + type);
    }
  }
}
